### ISSUE TITLE
total_consultations and total_cases to epi_monitoring API call

### ISSUE THREAD

**Issue by jsoppela** [meerkat-code/meerkat_api#17]
epi_monitoring report API call to include:
- total consultations
- total cases
- deaths
- maternal deaths
- alerts generated
- alerts investigated

**Comment by mrjb** [comment]
Hi Jyri,  I'll have this sorted by the end of the day. Just so you know, the final four values are already included in the dump, so respectively: 
- (not included yet - will find somewhere sensible to include this)
- (not included yet - will find somewhere sensible to include this)
- tot_mortality.dea_0
- mat_mortality.mat_0
- alerts.generated
- alerts.investigated

It's probably sensible to build the system so the whole thing doesn't fail if one piece of information isn't available. So can you work around the first two until I tidied up my github tree mess and committed the malaria report?  Should have finished this by the end of this morning/early afternoon.

**Comment by jsoppela** [comment]
Thanks Jonathan! I'll leave out the parts that require the missing data for now. I'll have a better look tomorrow as I've booked the office hours for meerkat.

**Comment by mrjb** [comment]
Ok the first two are now added and pushed to master, so the complete list is:
-     email.consultations
-     email.cases
-     tot_mortality.dea_0
-     mat_mortality.mat_0
-     alerts.generated
-     alerts.investigated

**Comment by jsoppela** [comment]
Thanks! Does the epi_monitoring api call have the number of clinics? I can also check the api dumps myself if you give instructions.

**Comment by mrjb** [comment]
No I don't think it does.  Do you want me to add it?
