### ISSUE TITLE
API test for completeness fails in January.

### ISSUE THREAD

**Issue by mixmixmix** [meerkat-code/meerkat_api#29]
Defined in `test_data/locations.py`, clinic 7 starts reporting in February of a current year and completeness test is calculated assuming it already reports.
I can fix that, adding a case in the completeness test. Ok?

**Comment by Gulfa** [comment]
Thanks for pointing this out. I am working on sorting out completeness at the moment so I can fix the tests as well.

**Comment by jonathansberry** [comment]
All issues have been moved to the meerkat_issues repo.
